version: '3.4'

services:
  webmvc:
    image: regtansfers/rtcodingexercise-webmvc
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile
    depends_on:
      - sqldata
      - catalog-api

  catalog-api:
    image: regtansfers/rtcodingexercise-catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 1433:1433
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - "15672:15672"
    - "5672:5672"